#! /bin/bash
# find-utf-8-text --- accepts one or more arguments, and outputs a line for
# each argument that names an non-ASCII or UTF text file

is_not_ascii(){
    if [ -f "$1" ]
    then
	let nonASCII=$((`grep -P -c -- "[^\x00-\x7F]" "$1"`))
	if (($nonASCII!=0))
	then
	    echo "$1"
	fi
    fi
}

for arg in "$@"
do
    newarg=`echo "$arg" | sed 's/ /\\ /g'`
    if [ `echo "$arg" | head -c 1` == "-" ]; then newarg="./""$arg"; fi
    if [ -d "$newarg" ]
    then
	let n=1
	while (($n<=`find -- "$newarg" | wc -l`))
	do
	    file=`find -- "$newarg" | sed -n "$n"p`
	    is_not_ascii "$file"
	    let n=n+1
	done
    elif [ -f "$newarg" ]
    then
	is_not_ascii "$newarg"
    fi
done
