#! /bin/bash
# find-ascii-text --- accepts one or more arguments, and outputs a line for each argument that names an ASCII text file

is_ascii(){
    let nonASCII=`awk '/[^\t\f -~]/' $1 | wc -m`
    if (($nonASCII==0))
    then
	echo $1
    fi
}

for arg in "$@"
do
    if [ -d $arg ]
    then
	echo "DIRECTORY"
    elif [ -f $arg ]
    then
	is_ascii $arg
    else
	echo "DOES NOT EXIST"
    fi
done
