#! /bin/bash
# find-ascii-text --- accepts one or more arguments, and outputs a line for each argument that names an ASCII text file

is_ascii(){
    if [ -f "$1" ]
    then
	let nonASCII=`grep -P -n "[^\x00-\x7F]" $1 | wc -m`
	if (($nonASCII==0))
	then
	    echo $1
	fi
    fi
}

for arg in "$@"
do
    if [ -d $arg ]
    then
	let n=2
	while (($n<=`find $arg | wc -l`))
	do
	    file=`find $arg | sed -n "$n"p`
	    is_ascii $file
	    let n=n+1
	done
    elif [ -f $arg ]
    then
	is_ascii $arg
    else
	echo "DOES NOT EXIST"
    fi
done
