#! /bin/bash
# testScript --- testing shell scripting

grep Hawaii.. assign2.html

Var='hello world'
echo $Var
myvar=helloworld
echo $myvar
myvar2=$myvar
echo $myvar2

let z=5
let a=$z+5
echo $z
echo $a

((b=z+a))
echo $b

ls

echo ls
echo `ls`

if [ "10" -lt "15" ]
then
	echo true
fi
