#! /bin/bash
# find-ascii-text --- accepts one or more arguments, and outputs a line for each argument that names an ASCII text file

if [ -d "$1" ]
then
    echo "DIRECTORY"
elif [ -f "$1" ]
then
    echo "FILE"
else
    echo "DOES NOT EXIST"
fi
